
Metrics/BlockLength:
  Max: 29

Metrics/LineLength:
  Max: 95
  Exclude:
    - lib/capistrano/backup/helpers.rb

# snake case files
Style/FileName:
  Exclude:
    - 'lib/capistrano-backup.rb'

Style/StringLiterals:
  Enabled:
    false
